---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keydb.keydb
  resources:
  - keydbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keydb.keydb
  resources:
  - keydbs/finalizers
  verbs:
  - update
- apiGroups:
  - keydb.keydb
  resources:
  - keydbs/status
  verbs:
  - get
  - patch
  - update
