apiVersion: keydb.keydb/v1
kind: Keydb
metadata:
  labels:
    app.kubernetes.io/name: keydb-operator
    app.kubernetes.io/managed-by: kustomize
  name: keydb
  namespace: default
spec:
  replicas: 3
  image: eqalpha/keydb
  password: password
  persistence:
    enabled: true
    size: 1Gi
  replication:
    mode: master-master
    enabled: true
    domain: keydb-svc.two:6379
