apiVersion: keydb.keydb/v1
kind: Keydb
metadata:
  labels:
    app.kubernetes.io/name: keydb-operator
    app.kubernetes.io/managed-by: kustomize
  name: keydb
  namespace: default
spec:
  replicas: 3
  image: bitnamilegacy/keydb:latest
  persistence:
    enabled: true
    size: 1Gi
  replication:
    mode: master-master
    enabled: true
    domain:
      - keydb-two-headless.default.svc.cluster.local
    port: 6379
  metrics:
    enabled: true
    image: oliver006/redis_exporter:latest
