apiVersion: keydb.keydb/v1
kind: Keydb
metadata:
  labels:
    app.kubernetes.io/name: keydb-operator
    app.kubernetes.io/managed-by: kustomize
  name: keydb-new
  namespace: default
spec:
  replicas: 3
  image: eqalpha/keydb
